### ISSUE TITLE
npm install crash

### ISSUE THREAD

**Issue by achimdehnert** [jackdh/RasaTalk#26]
Hi, I like very much what you are doing! UNfortunatelly I am stuck

what I have: Ubuntu 18.04 conda venv python 3.6 rasa_coree and rasa_nla stable

when I start "sudo npm install" I get an error, see below
I already tried: sudo chown -R $USER:$(id -gn $USER) /home/dehnert/.config

(dehn_rasa0) dehnert@vmd37935:/RasaTalk$ sudo npm install
npm WARN lifecycle rasa-talk@1.1.0preinstall: cannot run in wd rasa-talk@1.1.0 npm run npmcheckversion (wd=/home/dehnert/RasaTalk)

    cwebp-bin@4.0.0 postinstall /home/dehnert/RasaTalk/node_modules/cwebp-bin
    node lib/install.js
    ⚠ EACCES: permission denied, mkdir '/home/dehnert/RasaTalk/node_modules/cwebp-bin/vendor'
    ⚠ cwebp pre-build test failed
    ℹ compiling from source
    /home/dehnert/RasaTalk/node_modules/each-async/node_modules/onetime/index.js:15
    throw new Error(fnName + ' can only be called once.');
    ^
    Error: callback() can only be called once.
    at onetime (/home/dehnert/RasaTalk/node_modules/each-async/node_modules/onetime/index.js:15:11)
    at /home/dehnert/RasaTalk/node_modules/download/index.js:156:5
    at ConcatStream. (/home/dehnert/RasaTalk/node_modules/concat-stream/index.js:37:43)
    at ConcatStream.emit (events.js:194:15)
    at finishMaybe (/home/dehnert/RasaTalk/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:630:14)
    at endWritable (/home/dehnert/RasaTalk/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at ConcatStream.Writable.end (/home/dehnert/RasaTalk/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:594:41)
    at DuplexWrapper.onend (/home/dehnert/RasaTalk/node_modules/duplexer2/node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:277:13)
    at DuplexWrapper.emit (events.js:194:15)
    npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
    npm WARN redux-form-material-ui@5.0.0-beta.3 requires a peer of @material-ui/core@1 but none is installed. You must install peer dependencies yourself.
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! cwebp-bin@4.0.0 postinstall: node lib/install.js
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the cwebp-bin@4.0.0 postinstall script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    npm ERR! A complete log of this run can be found in:
    npm ERR! /home/dehnert/.npm/_logs/2019-04-05T06_21_42_704Z-debug.log
    (dehn_rasa0) dehnert@vmd37935:~/RasaTalk$

any advice / Hint is highly welcome
with kind regards
achim

**Comment by achimdehnert** [comment]
Hi, I like very much what you are doing! UNfortunatelly I am stuck

what I have:  Ubuntu 18.04 conda venv python 3.6 rasa_coree and rasa_nla stable 

when I start "sudo npm install"  I get an error,  see below
I already tried:   sudo chown -R $USER:$(id -gn $USER) /home/dehnert/.config 

(dehn_rasa0) dehnert@vmd37935:~/RasaTalk$ sudo npm install
npm WARN lifecycle rasa-talk@1.1.0~preinstall: cannot run in wd rasa-talk@1.1.0 npm run npmcheckversion (wd=/home/dehnert/RasaTalk)
> cwebp-bin@4.0.0 postinstall /home/dehnert/RasaTalk/node_modules/cwebp-bin
> node lib/install.js
  ⚠ EACCES: permission denied, mkdir '/home/dehnert/RasaTalk/node_modules/cwebp-bin/vendor'
  ⚠ cwebp pre-build test failed
  ℹ compiling from source
/home/dehnert/RasaTalk/node_modules/each-async/node_modules/onetime/index.js:15
                                throw new Error(fnName + ' can only be called once.');
                                ^
Error: callback() can only be called once.
    at onetime (/home/dehnert/RasaTalk/node_modules/each-async/node_modules/onetime/index.js:15:11)
    at /home/dehnert/RasaTalk/node_modules/download/index.js:156:5
    at ConcatStream.<anonymous> (/home/dehnert/RasaTalk/node_modules/concat-stream/index.js:37:43)
    at ConcatStream.emit (events.js:194:15)
    at finishMaybe (/home/dehnert/RasaTalk/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:630:14)
    at endWritable (/home/dehnert/RasaTalk/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at ConcatStream.Writable.end (/home/dehnert/RasaTalk/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:594:41)
    at DuplexWrapper.onend (/home/dehnert/RasaTalk/node_modules/duplexer2/node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:277:13)
    at DuplexWrapper.emit (events.js:194:15)
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN redux-form-material-ui@5.0.0-beta.3 requires a peer of @material-ui/core@1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cwebp-bin@4.0.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cwebp-bin@4.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dehnert/.npm/_logs/2019-04-05T06_21_42_704Z-debug.log
(dehn_rasa0) dehnert@vmd37935:~/RasaTalk$

any advice / Hint is highly welcome
with kind regards 
achim

**Comment by jackdh** [comment]
Hey,

this looks like a permission issue on your machine.

I would first suggest not using `sudo` with `npm install`, then secondly trying outside of a Virtual Python Environment if you can.

**Comment by jackdh** [comment]
Hey @achimdehnert I've not seen a reply so I'm going to close this for now!
